package pow.crimson2.managers;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import io.papermc.paper.registry.RegistryAccess;
import io.papermc.paper.registry.RegistryKey;
import org.bukkit.*;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.ItemType;
import org.bukkit.plugin.java.JavaPlugin;
import pow.crimson2.VampireSMPPlugin;
import pow.crimson2.beacons.BeaconSite;
import pow.crimson2.utils.LeveledEnchantment;

public class ConfigManager {
   private final VampireSMPPlugin plugin;
   private FileConfiguration config;

   public ConfigManager(VampireSMPPlugin plugin) {
      this.plugin = plugin;
      this.loadConfig();
   }

   public void loadConfig() {
      this.plugin.saveDefaultConfig();
      this.plugin.reloadConfig();
      // Merge any newly-added default keys (from plugin updates) into the on-disk config
      // without overwriting the values already set there. This keeps the in-game config
      // editor showing every available setting, even on servers generated by older builds.
      this.plugin.getConfig().options().copyDefaults(true);
      this.plugin.saveConfig();
      this.config = this.plugin.getConfig();
   }

   public void saveConfig() {
      this.plugin.saveConfig();
   }

   public boolean isCureBooksEnabled() {
      return this.config.getBoolean("cure_books_enabled", true);
   }

   public double getCureBooksSpawnChance() {
      return this.config.getDouble("cure_books_spawn_chance", 0.3);
   }

   public boolean isFirstMessageBlockingEnabled() {
      return this.config.getBoolean("chat.first-message-blocking-enabled", true);
   }

   public String getFirstMessageBlockedMessage() {
      return this.config
              .getString(
                      "chat.first-message-blocked-message",
                      "&eIt looks like you've attempted to send a message! Vampire SMP is geared to revolve around immersion, consider finding the person you need to speak to, or messaging them on discord. If you still need to send your chat message, [Click Here]&e. This prevention message will not appear again until your next log on if you do choose to send your message via the blue text."
              );
   }

   public long getTomeDistributionIntervalTicks() {
      int minutes = this.config.getInt("tome-distribution-interval-minutes", 20);
      return minutes * 60L * 20L;
   }

   public List<Location> getTomeChestLocations() {
      List<String> locationStrings = this.config.getStringList("tome-chests.locations");
      List<Location> locations = new ArrayList<>();
      World world = this.plugin.getWorld();
      if (world == null) {
         this.plugin.getLogger().severe("World not found! Cannot load tome chest locations.");
         return locations;
      }

      for (String locString : locationStrings) {
         try {
            String[] parts = locString.split(",");
            if (parts.length == 3) {
               int x = Integer.parseInt(parts[0].trim());
               int y = Integer.parseInt(parts[1].trim());
               int z = Integer.parseInt(parts[2].trim());
               locations.add(new Location(world, x, y, z));
            }
         } catch (NumberFormatException e) {
            this.plugin.getLogger().warning("Invalid tome chest location format: " + locString);
         }
      }

      return locations;
   }

   public int getTomeCount() {
      return this.config.getInt("tome-chest-items.tome-count", 4);
   }

   public List<String> getTomeTypes() {
      List<String> tomeTypes = this.config.getStringList("tome-chest-items.tomes-available");
      if (tomeTypes.isEmpty()) {
         return Arrays.asList(
                 "BanishUndead",
                 "Blessing",
                 "EnlightenedEye",
                 "HolyWord",
                 "LanternThrash",
                 "PrayerOfFaith",
                 "RallyingCry",
                 "ShoulderBarge",
                 "TurnUndead",
                 "UncannyDirection",
                 "UnnaturalHaste",
                 "WayOfTheLand",
                 "WayOfTheLumberjack",
                 "WayOfTheProspector"
         );
      } else {
         return tomeTypes;
      }
   }

   public List<LeveledEnchantment> getTomeEnchantmentTypes() {
      List<String> enchantStrings = this.config.getStringList("tome-chest-items.enchantments-available");
      List<LeveledEnchantment> enchants = new ArrayList<>();
      Registry<Enchantment> enchantReg = RegistryAccess.registryAccess().getRegistry(RegistryKey.ENCHANTMENT);
      for (String enchantString : enchantStrings) {
         String[] parts = enchantString.split(" ");
         try {
            assert parts.length == 2;
            Enchantment enchant = enchantReg.get(NamespacedKey.minecraft(parts[0]));
            if (enchant == null) {
               this.plugin.getLogger().warning("Unknown enchantment: " + parts[0]);
               continue;
            }
            int level = Integer.parseInt(parts[1]);
            enchants.add(new LeveledEnchantment(enchant, level));
         } catch (Exception e) {
            this.plugin.getLogger().warning("Invalid enchantment format: " + enchantString);
         }
      }
      if (enchants.isEmpty()) {
         return Arrays.asList(
                 new LeveledEnchantment(Enchantment.EFFICIENCY, 1),
                 new LeveledEnchantment(Enchantment.PROTECTION, 1),
                 new LeveledEnchantment(Enchantment.FEATHER_FALLING, 1),
                 new LeveledEnchantment(Enchantment.KNOCKBACK, 1),
                 new LeveledEnchantment(Enchantment.SWEEPING_EDGE, 1)
         );
      } else {
         return enchants;
      }
   }

   public int getTomeMiscCount() {
      return this.config.getInt("tome-chest-items.misc-items-count", 0);
   }

   public List<ItemStack> getTomeMiscTypes() {
      List<String> miscStrings = this.config.getStringList("tome-chest-items.misc-items");
      List<ItemStack> miscItems = new ArrayList<>();
      for (String miscString : miscStrings) {
         String[] parts = miscString.split(" ");
         try {
            assert parts.length <= 2;
            int count = 1;
            if (parts.length == 2) {
               count = Integer.parseInt(parts[1]);
            }
            Material mat = Material.getMaterial(parts[0]);
            if (mat == null) {
               this.plugin.getLogger().warning("Unknown item: " + parts[0]);
               continue;
            }
            miscItems.add(new ItemStack(mat, count));
         } catch (Exception e) {
            this.plugin.getLogger().warning("Invalid item format: " + miscString);
         }
      }
      return miscItems;
   }

   public boolean addTomeChestLocation(Location location) {
      List<String> locations = this.config.getStringList("tome-chests.locations");
      String locationString = String.format("%d,%d,%d", location.getBlockX(), location.getBlockY(), location.getBlockZ());
      if (locations.contains(locationString)) {
         return false;
      }

      locations.add(locationString);
      this.config.set("tome-chests.locations", locations);
      this.saveConfig();
      return true;
   }

   public boolean removeTomeChestLocation(Location location) {
      List<String> locations = this.config.getStringList("tome-chests.locations");
      String locationString = String.format("%d,%d,%d", location.getBlockX(), location.getBlockY(), location.getBlockZ());
      if (!locations.contains(locationString)) {
         return false;
      }

      locations.remove(locationString);
      this.config.set("tome-chests.locations", locations);
      this.saveConfig();
      return true;
   }

   public int getVampireBatCooldown() {
      return this.config.getInt("abilities.vampire.bat-cooldown", 900);
   }

   public int getVampireBatCooldownStage(int stage) {
      int fallback = getVampireBatCooldown();
      return this.config.getInt("abilities.vampire.bat-cooldown-stage" + stage, fallback);
   }

   public int getVampireBatDurationSeconds(int stage) {
      // fallback chain: stage-specific → old bat-duration-seconds → 120
      int base = this.config.getInt("abilities.vampire.bat-duration-seconds", 120);
      return this.config.getInt("abilities.vampire.bat-duration-seconds-stage" + stage, base);
   }

   public int getVampireLungeCooldown() {
      return this.config.getInt("abilities.vampire.lunge-cooldown", 45);
   }

   public int getVampireLungeCooldownStage(int stage) {
      int fallback = getVampireLungeCooldown();
      return this.config.getInt("abilities.vampire.lunge-cooldown-stage" + stage, fallback);
   }

   public double getVampireLungeStrengthStage(int stage) {
      double def = stage >= 3 ? 2.5 : 2.0;
      return this.config.getDouble("abilities.vampire.lunge-strength-stage" + stage, def);
   }

   public int getVampireVanishCooldown() {
      return this.config.getInt("abilities.vampire.vanish-cooldown", 420);
   }

   public int getVampireVanishCooldownStage(int stage) {
      int fallback = getVampireVanishCooldown();
      return this.config.getInt("abilities.vampire.vanish-cooldown-stage" + stage, fallback);
   }

   public int getVampireVanishDurationTicks(int stage) {
      // old hardcoded values: stage2=2400t(120s), stage3=4800t(240s)
      int defaultSeconds = stage >= 3 ? 240 : 120;
      int seconds = this.config.getInt("abilities.vampire.vanish-duration-seconds-stage" + stage, defaultSeconds);
      return seconds * 20;
   }

   public int getVampireStormCallCooldown() {
      return this.config.getInt("abilities.vampire.storm-call-cooldown", 7200);
   }

   public int getVampireStormCallDurationSeconds() {
      return this.config.getInt("abilities.vampire.storm-call-duration-seconds", 600);
   }

   public int getVampireBeaconTeleportCooldown() {
      return this.config.getInt("abilities.vampire.beacon-teleport-cooldown", 300);
   }

   public int getVampireBeaconTeleportCooldownStage(int stage) {
      int fallback = getVampireBeaconTeleportCooldown();
      return this.config.getInt("abilities.vampire.beacon-teleport-cooldown-stage" + stage, fallback);
   }

   public boolean getBeaconTeleportRequireFullHealth() {
      return this.config.getBoolean("abilities.vampire.beacon-teleport-require-full-health", true);
   }

   public int getVanishAttackLimitStage2() {
      return this.config.getInt("abilities.vampire.vanish-attack-limit-stage2", 3);
   }

   public int getVanishAttackLimitStage3() {
      return this.config.getInt("abilities.vampire.vanish-attack-limit-stage3", 3);
   }

   public int getVampireVisionCooldown() {
      return this.config.getInt("abilities.vampire.vampire-vision-cooldown", 1);
   }

   public int getTomeBlessingCooldown() {
      return this.config.getInt("abilities.tome.blessing-cooldown", 7200);
   }

   public int getTomeBanishUndeadCooldown() {
      return this.config.getInt("abilities.tome.banish-undead-cooldown", 900);
   }

   public int getTomeHolyWordCooldown() {
      return this.config.getInt("abilities.tome.holy-word-cooldown", 600);
   }

   public int getTomeEnlightenedEyeCooldown() {
      return this.config.getInt("abilities.tome.enlightened-eye-cooldown", 900);
   }

   public int getTomeLanternThrashCooldown() {
      return this.config.getInt("abilities.tome.lantern-thrash-cooldown", 300);
   }

   public int getTomePrayerOfFaithCooldown() {
      return this.config.getInt("abilities.tome.prayer-of-faith-cooldown", 900);
   }

   public int getTomeRallyingCryCooldown() {
      return this.config.getInt("abilities.tome.rallying-cry-cooldown", 1200);
   }

   public int getTomeShoulderBargeCooldown() {
      return this.config.getInt("abilities.tome.shoulder-barge-cooldown", 300);
   }

   public int getTomeTurnUndeadCooldown() {
      return this.config.getInt("abilities.tome.turn-undead-cooldown", 1800);
   }

   public int getTomeUncannyDirectionCooldown() {
      return this.config.getInt("abilities.tome.uncanny-direction-cooldown", 30);
   }

   public int getTomeUnnaturalHasteCooldown() {
      return this.config.getInt("abilities.tome.unnatural-haste-cooldown", 900);
   }

   public int getTomeWayOfTheLandCooldown() {
      return this.config.getInt("abilities.tome.way-of-the-land-cooldown", 600);
   }

   public int getTomeWayOfTheLumberjackCooldown() {
      return this.config.getInt("abilities.tome.way-of-the-lumberjack-cooldown", 600);
   }

   public int getTomeWayOfTheProspectorCooldown() {
      return this.config.getInt("abilities.tome.way-of-the-prospector-cooldown", 600);
   }

   public int getTomeStopTheBleedingCooldown() {
      return this.config.getInt("abilities.tome.stop-the-bleeding-cooldown", 7200);
   }

   public int getTomeFireBreathCooldown() {
      return this.config.getInt("abilities.tome.firebreath.cooldown", 600);
   }

   public double getTomeFireBreathRange() {
      return this.config.getDouble("abilities.tome.firebreath.range", 8.0);
   }

   public double getTomeFireBreathConeAngle() {
      return this.config.getDouble("abilities.tome.firebreath.cone-angle", 35.0);
   }

   public int getTomeFireBreathDurationTicks() {
      return this.config.getInt("abilities.tome.firebreath.duration-ticks", 20);
   }

   public int getTomeFireBreathParticlesPerTick() {
      return this.config.getInt("abilities.tome.firebreath.particles-per-tick", 28);
   }

   public double getTomeFireBreathDamage() {
      return this.config.getDouble("abilities.tome.firebreath.damage", 4.0);
   }

   public int getTomeFireBreathFireTicks() {
      return this.config.getInt("abilities.tome.firebreath.fire-ticks", 100);
   }

   public int getTomeBlueFireBreathCooldown() {
      return this.magicFireInt("cooldown", 900);
   }

   public double getTomeBlueFireBreathRange() {
      return this.magicFireDouble("range", 12.0);
   }

   public double getTomeBlueFireBreathConeAngle() {
      return this.magicFireDouble("cone-angle", 28.0);
   }

   public int getTomeBlueFireBreathDurationTicks() {
      return this.magicFireInt("duration-ticks", 25);
   }

   public int getTomeBlueFireBreathParticlesPerTick() {
      return this.magicFireInt("particles-per-tick", 32);
   }

   public double getTomeBlueFireBreathDamage() {
      return this.magicFireDouble("damage", 6.0);
   }

   public int getTomeBlueFireBreathFireTicks() {
      return this.magicFireInt("fire-ticks", 160);
   }

   private int magicFireInt(String key, int fallback) {
      String current = "abilities.tome.magicfirebreath." + key;
      String legacy = "abilities.tome.bluefirebreath." + key;
      return this.config.contains(current) ? this.config.getInt(current) : this.config.getInt(legacy, fallback);
   }

   private double magicFireDouble(String key, double fallback) {
      String current = "abilities.tome.magicfirebreath." + key;
      String legacy = "abilities.tome.bluefirebreath." + key;
      return this.config.contains(current) ? this.config.getDouble(current) : this.config.getDouble(legacy, fallback);
   }

   public int getThirstDepletionMinutes() {
      return this.config.getInt("thirst.depletion-minutes", 120);
   }

   public int getMaxFeedingThirstPerSession() {
      return this.config.getInt("thirst.max-feeding-per-session", 60);
   }

   public Location getVampireRespawnLocation(World world) {
      String locationStr = this.config.getString("vampire.respawn-location", "40,101,-113");
      String[] parts = locationStr.split(",");

      try {
         double x = Double.parseDouble(parts[0].trim());
         double y = Double.parseDouble(parts[1].trim());
         double z = Double.parseDouble(parts[2].trim());
         return new Location(world, x, y, z);
      } catch (Exception e) {
         this.plugin.getLogger().warning("Invalid vampire respawn location format: " + locationStr + ". Using default.");
         return new Location(world, 40.0, 101.0, -113.0);
      }
   }

   public void setVampireRespawnLocation(String locationStr) {
      this.config.set("vampire.respawn-location", locationStr);
      this.plugin.saveConfig();
   }

   public boolean getDisableTurningAfterTurn() { return this.config.getBoolean("vampire.disable-turning-after-turn", true); }

   public double getCureBeaconDistance() {
      return this.config.getDouble("cure.cure-distance", 25.0);
   }

   public int getCureSireLineLength() { return this.config.getInt("cure.sire-line-length", 1); }

   public boolean getCureAllowCuredSire() { return this.config.getBoolean("cure.allow-cured-sire", false); }

   public boolean getCureNeedsDaytime() { return this.config.getBoolean("cure.needs-daytime", true); }

   public boolean getTrackingEnabled() { return this.config.getBoolean("vampire-indicator.enabled", true); }

   public int getTrackingDurationSeconds() { return this.config.getInt("vampire-indicator.duration-seconds", 120); }

   public double getTrackingDistance() { return this.config.getDouble("vampire-indicator.distance", 0); }

   public boolean getTrackingArrowEnabled() { return this.config.getBoolean("vampire-indicator.tracker", true); }

   public int getTrackingMinimumStage() { return this.config.getInt("vampire-indicator.minimum-stage", 1); }

   public long getBeaconConversionTimeMs() {
      long seconds = this.config.getLong("beacons.conversion-time-seconds", 300L);
      return seconds * 1000L;
   }

   public long getBeaconConversionCooldownMs() {
      long minutes = this.config.getLong("beacons.conversion-cooldown-minutes", 60L);
      return minutes * 60L * 1000L;
   }

   public double getBeaconHumanSpeedMultiplier() {
      return this.config.getDouble("beacons.human-speed-multiplier", 1.5);
   }

   public double getBeaconFinalStandMultiplier() {
      return this.config.getDouble("beacons.final-stand-multiplier", 6.0);
   }

   public int getBeaconNeutralAnnouncementDelaySeconds() {
      return this.config.getInt("beacons.neutral-announcement-delay-seconds", 60);
   }

   public boolean doCorruptedBeaconsTrapHumans() {
      return this.config.getBoolean("beacons.corrupted-beacons-trap-humans", true);
   }

   public int getGarlicProcessingTimeMin() {
      return this.config.getInt("garlic.processing-time-min-seconds", 480);
   }

   public int getGarlicProcessingTimeMax() {
      return this.config.getInt("garlic.processing-time-max-seconds", 720);
   }

   public int getGarlicImmunityDurationMin() {
      return this.config.getInt("garlic.immunity-duration-min-seconds", 480);
   }

   public int getGarlicImmunityDurationMax() {
      return this.config.getInt("garlic.immunity-duration-max-seconds", 600);
   }

   public boolean isNonEssentialLoggingDisabled() {
      return this.config.getBoolean("disable-nonessential-logging", false);
   }

   public int getHolyWaterDisableDurationSeconds() {
      return this.config.getInt("holy-water.disable-duration-seconds", 120);
   }

   public boolean isPassiveMobAutoSpawnEnabled() {
      return this.config.getBoolean("passive-mob-spawning.auto-spawn-enabled", true);
   }

   public int getPassiveMobMinimumThreshold() {
      return this.config.getInt("passive-mob-spawning.minimum-animal-threshold", 40);
   }

   public int getPassiveMobSpawnCount() {
      return this.config.getInt("passive-mob-spawning.spawn-count", 80);
   }

   public int getPermadeathMinimumStage() {
      return this.config.getInt("combat.permadeath-minimum-stage", 1);
   }

   public int getWoodenStakeCooldownTicks() {
      return this.config.getInt("combat.wooden-stake-cooldown-ticks", 80);
   }

   public String getOakhurstName() {
      return this.config.getString("oakhurst.name", "Oakhurst");
   }

   public double getOakhurstTownCenterX() {
      return this.config.getDouble("oakhurst.town-center-x", 79.0);
   }

   public double getOakhurstTownCenterZ() {
      return this.config.getDouble("oakhurst.town-center-z", 440.0);
   }

   public double getOakhurstTeleportRadius() {
      return this.config.getDouble("oakhurst.teleport-radius", 400.0);
   }

   public double getOakhurstBorderCenterX() {
      return this.config.getDouble("oakhurst.border.center-x", 50.0);
   }

   public double getOakhurstBorderCenterZ() {
      return this.config.getDouble("oakhurst.border.center-z", 50.0);
   }

   public double getOakhurstBorderDiameter() {
      return this.config.getDouble("oakhurst.border.diameter", 1098.0);
   }

   public double getOakhurstBorderRadius() {
      return this.getOakhurstBorderDiameter() / 2.0;
   }

   public double getOakhurstMinX() {
      return this.getOakhurstBorderCenterX() - this.getOakhurstBorderRadius();
   }

   public double getOakhurstMaxX() {
      return this.getOakhurstBorderCenterX() + this.getOakhurstBorderRadius();
   }

   public double getOakhurstMinZ() {
      return this.getOakhurstBorderCenterZ() - this.getOakhurstBorderRadius();
   }

   public double getOakhurstMaxZ() {
      return this.getOakhurstBorderCenterZ() + this.getOakhurstBorderRadius();
   }

   // ============================================================================
   // WEREWOLF COMBAT
   // ============================================================================

   public double getWerewolfSilverWeaknessMultiplier() {
      return this.config.getDouble("werewolf.combat.silver-weakness-multiplier", 1.75);
   }

   public double getWerewolfFistMultiplierStage2() {
      return this.config.getDouble("werewolf.combat.fist-multiplier-stage2", 1.5);
   }

   public double getWerewolfFistMultiplierStage3() {
      return this.config.getDouble("werewolf.combat.fist-multiplier-stage3", 2.5);
   }

   // ============================================================================
   // WEREWOLF BITING
   // ============================================================================

   public double getWerewolfBiteMaxDistance() {
      return this.config.getDouble("werewolf.biting.max-distance", 3.5);
   }

   public int getWerewolfBiteNotifyTicks() {
      return this.config.getInt("werewolf.biting.notify-ticks", 200);
   }

   public int getWerewolfBiteCompleteTicks() {
      return this.config.getInt("werewolf.biting.complete-ticks", 300);
   }

   // ============================================================================
   // WEREWOLF PACK BONUS
   // ============================================================================

   public double getWerewolfPackRadius() {
      return this.config.getDouble("werewolf.pack.radius", 20.0);
   }

   public int getWerewolfPackEffectDurationTicks() {
      return this.config.getInt("werewolf.pack.effect-duration-ticks", 80);
   }

   public long getWerewolfPackCheckIntervalTicks() {
      return this.config.getLong("werewolf.pack.check-interval-ticks", 60L);
   }

   // ============================================================================
   // WEREWOLF HUNGER
   // ============================================================================

   public int getWerewolfHungerDepletionMinutes() {
      return this.config.getInt("werewolf.hunger.depletion-minutes", 20);
   }

   public float getWerewolfHungerPerMeat() {
      return (float) this.config.getDouble("werewolf.hunger.hunger-per-meat", 0.10);
   }

   // ============================================================================
   // WEREWOLF ABILITIES
   // ============================================================================

   public int getWerewolfFeralChargeCooldown() {
      return this.config.getInt("werewolf.abilities.feral-charge-cooldown", 12);
   }

   public double getWerewolfFeralChargePowerStage2() {
      return this.config.getDouble("werewolf.abilities.feral-charge-power-stage2", 2.0);
   }

   public double getWerewolfFeralChargePowerStage3() {
      return this.config.getDouble("werewolf.abilities.feral-charge-power-stage3", 3.0);
   }

   // ============================================================================
   // BEACONS — CAPTURE & TRAVEL
   // ============================================================================

   public int getHolyWordRadius() {
      return this.config.getInt("abilities.tome.holyword.radius", 20);
   }

   public int getHolyWordParalysisDurationTicks() {
      return this.config.getInt("abilities.tome.holyword.paralysis-duration-ticks", 300);
   }

   public int getShoulderBargeChargeDurationTicks() {
      return this.config.getInt("abilities.tome.shoulderbarge-charge.charge-duration-ticks", 20);
   }

   public double getShoulderBargeUpwardVelocity() {
      return this.config.getDouble("abilities.tome.shoulderbarge-charge.upward-velocity", 0.3);
   }

   public long getShoulderBargeTargetCooldownMs() {
      return this.config.getLong("abilities.tome.shoulderbarge-charge.target-cooldown-ms", 3000L);
   }

   public int getUncannyDirectionAnimationTicks() {
      return this.config.getInt("abilities.tome.uncannydirection.animation-ticks", 140);
   }

   public int getVampireStormClearWeatherTicks() {
      return this.config.getInt("abilities.vampire.storm-clear-weather-ticks", 6000);
   }

   public int getBeaconCaptureRadius() {
      return this.config.getInt("beacons.capture-radius", 10);
   }

   public int getBeaconTeleportChannelTicks() {
      return this.config.getInt("abilities.vampire.beacon-teleport-channel-ticks", 100);
   }

   // ============================================================================
   // COMBAT — DEATH / FINAL STAND
   // ============================================================================

   public double getHumanFinalStandHealthCap() {
      return this.config.getDouble("combat.humans-final-stand-health-cap", 6.0);
   }

   public int getHumanDeathScoreCap() {
      return this.config.getInt("combat.human-death-score-cap", 5);
   }

   public double getHumanDeathHpPenalty() {
      return this.config.getDouble("combat.human-death-hp-penalty", 2.0);
   }

   /** Death count at or above which a vampire kill is permanent. */
   public int getVampireKillPermadeathThreshold() {
      return this.config.getInt("combat.vampire-kill-permadeath-threshold", 5);
   }

   /**
    * When true the threshold applies to every vampire kill. When false it only applies if the
    * killing vampire had turning switched off — the pre-existing behaviour.
    */
   public boolean isVampireKillPermadeathAlways() {
      return this.config.getBoolean("combat.vampire-kill-permadeath-always", true);
   }

   // ============================================================================
   // ABILITIES — SURVIVING THE TURN  (allow.use.after.turned)
   // ============================================================================

   public boolean isAllowUseAfterTurned() {
      return this.config.getBoolean("allow.use.after.turned.enabled", false);
   }

   /** Whether allow-listed abilities keep their tags when the player is turned. */
   public boolean isKeepAbilitiesOnTurn() {
      return this.config.getBoolean("allow.use.after.turned.keep-on-turn", true);
   }

   /** Whether a turned player may also hold the physical tome books. */
   public boolean isAllowTomeItemsAfterTurned() {
      return this.config.getBoolean("allow.use.after.turned.allow-tome-items", false);
   }

   public java.util.List<String> getAbilitiesAllowedAfterTurned() {
      return this.config.getStringList("allow.use.after.turned.abilities");
   }

   /** True if this specific ability survives turning. "*" in the list means everything does. */
   public boolean isAbilityAllowedAfterTurned(String abilityName) {
      if (!this.isAllowUseAfterTurned() || abilityName == null) {
         return false;
      }
      for (String entry : this.getAbilitiesAllowedAfterTurned()) {
         if ("*".equals(entry) || entry.equalsIgnoreCase(abilityName)) {
            return true;
         }
      }
      return false;
   }

   public boolean isEveryAbilityAllowedAfterTurned() {
      return this.isAllowUseAfterTurned() && this.getAbilitiesAllowedAfterTurned().contains("*");
   }

   /** Add or remove an ability from the allow-list and persist it to config.yml. */
   public void setAbilityAllowedAfterTurned(String abilityName, boolean allowed) {
      java.util.List<String> current = new java.util.ArrayList<>(this.getAbilitiesAllowedAfterTurned());
      current.removeIf(entry -> entry.equalsIgnoreCase(abilityName));
      if (allowed) {
         current.add(abilityName);
      }
      this.config.set("allow.use.after.turned.abilities", current);
      this.saveConfig();
   }

   public void setAllowUseAfterTurned(boolean enabled) {
      this.config.set("allow.use.after.turned.enabled", enabled);
      this.saveConfig();
   }

   // ============================================================================
   // FAE — BARGAINS
   // ============================================================================

   public boolean isFaeEnabled() {
      return this.config.getBoolean("fae.enabled", true);
   }

   /** PERMADEATH (only a permanent death breaks bargains) or ANY_DEATH. */
   public String getFaeBreakDealsOn() {
      return this.config.getString("fae.break-deals-on", "PERMADEATH");
   }

   public boolean isFaeRevertToHumanOnBreak() {
      return this.config.getBoolean("fae.revert-to-human-on-break", true);
   }

   public boolean isFaeMarkCuredOnBreak() {
      return this.config.getBoolean("fae.mark-as-cured-on-break", false);
   }

   public boolean isFaeTurnedCannotTurn() {
      return this.config.getBoolean("fae.turned-cannot-turn", true);
   }

   public boolean isFaeStakingIgnoresMinimumStage() {
      return this.config.getBoolean("fae.staking-ignores-minimum-stage", true);
   }

   public boolean isFaeBroadcastOnBreak() {
      return this.config.getBoolean("fae.broadcast-on-break", true);
   }

   /** Whether a fae may aim the deaths/hearts/turn-lock subcommands at anyone, or only at their own deal targets. */
   public boolean isFaeAdminSubcommandsAnyPlayer() {
      return this.config.getBoolean("fae.subcommands-target-any-player", true);
   }

   public java.util.List<Integer> getFaeAllowedStages() {
      java.util.List<Integer> stages = this.config.getIntegerList("fae.allowed-stages");
      return stages == null || stages.isEmpty() ? java.util.Arrays.asList(1, 2, 3) : stages;
   }

   // ============================================================================
   // WEREWOLF — HUNGER IMMUNITY
   // ============================================================================

   public int getWerewolfHungerImmunityMinutes() {
      return this.config.getInt("werewolf.hunger.immunity-minutes", 15);
   }

   // ============================================================================
   // IRON WEAKNESS
   // ============================================================================

   public double getIronRepelDistance() {
      return this.config.getDouble("iron-weakness.repel-distance", 2.0);
   }

   public double getIronRepelStrength() {
      return this.config.getDouble("iron-weakness.repel-strength", 0.5);
   }

   public double getIronProximityRadius() {
      return this.config.getDouble("iron-weakness.proximity-radius", 5.0);
   }

   public int getIronWeaknessDurationTicks() {
      return this.config.getInt("iron-weakness.weakness-duration-ticks", 40);
   }

   public int getIronWeaknessAmplifier() {
      return this.config.getInt("iron-weakness.weakness-amplifier", 2);
   }

   // ============================================================================
   // PASSIVE MOB SPAWNING — WEIGHTS
   // ============================================================================

   public java.util.Map<org.bukkit.entity.EntityType, Integer> getPassiveMobSpawnWeights() {
      java.util.Map<org.bukkit.entity.EntityType, Integer> weights = new java.util.LinkedHashMap<>();
      org.bukkit.configuration.ConfigurationSection section = this.config.getConfigurationSection("passive-mob-spawning.mob-weights");
      if (section != null) {
         for (String key : section.getKeys(false)) {
            try {
               org.bukkit.entity.EntityType type = org.bukkit.entity.EntityType.valueOf(key.toUpperCase());
               int weight = section.getInt(key, 0);
               if (weight > 0) weights.put(type, weight);
            } catch (IllegalArgumentException ignored) {
               this.plugin.getLogger().warning("[WerePires] Unknown entity type in passive-mob-spawning.mob-weights: " + key);
            }
         }
      }
      if (weights.isEmpty()) {
         weights.put(org.bukkit.entity.EntityType.COW, 30);
         weights.put(org.bukkit.entity.EntityType.PIG, 30);
         weights.put(org.bukkit.entity.EntityType.SHEEP, 25);
         weights.put(org.bukkit.entity.EntityType.CHICKEN, 15);
      }
      return weights;
   }

   public boolean isLocationWithinBorder(double x, double z) {
      return x >= this.getOakhurstMinX() && x <= this.getOakhurstMaxX() && z >= this.getOakhurstMinZ() && z <= this.getOakhurstMaxZ();
   }

   public List<String> validateConfiguredLocations(BeaconManager beaconManager) {
      List<String> warnings = new ArrayList<>();
      double townX = this.getOakhurstTownCenterX();
      double townZ = this.getOakhurstTownCenterZ();
      if (!this.isLocationWithinBorder(townX, townZ)) {
         warnings.add("Town center (" + (int)townX + ", " + (int)townZ + ")");
      }

      World world = this.plugin.getWorld();
      if (world != null) {
         Location vampireSpawn = this.getVampireRespawnLocation(world);
         if (vampireSpawn != null && !this.isLocationWithinBorder(vampireSpawn.getX(), vampireSpawn.getZ())) {
            warnings.add("Vampire respawn (" + vampireSpawn.getBlockX() + ", " + vampireSpawn.getBlockZ() + ")");
         }

         for (Location loc : this.getTomeChestLocations()) {
            if (loc != null && !this.isLocationWithinBorder(loc.getX(), loc.getZ())) {
               warnings.add("Tome chest at (" + loc.getBlockX() + ", " + loc.getBlockZ() + ")");
            }
         }
      }

      if (beaconManager != null) {
         for (BeaconSite beacon : beaconManager.getAllBeacons()) {
            Location loc = beacon.getLocation();
            if (loc == null) {
               // Beacon's world isn't loaded/resolving — skip (and surface it).
               warnings.add("Beacon '" + beacon.getName() + "' — world '" + beacon.getWorldName() + "' not loaded");
               continue;
            }
            if (!this.isLocationWithinBorder(loc.getX(), loc.getZ())) {
               warnings.add("Beacon '" + beacon.getName() + "' (" + loc.getBlockX() + ", " + loc.getBlockZ() + ")");
            }
         }
      }

      return warnings;
   }
}
